### ISSUE TITLE
Should --open parameter be added to start script

### ISSUE THREAD

**Issue by winksaville** [angular/devkit#120]
In the [Tour of Heros](https://angular.io/tutorial) tutorial [here](https://angular.io/tutorial/toh-pt1#keep-the-app-transpiling-and-running) and [here](https://angular.io/tutorial/toh-pt2#keep-the-app-transpiling-and-running) it says:
```
$ npm start

This command runs the TypeScript compiler in "watch mode",
recompiling automatically when the code changes. The command
simultaneously launches the app in a browser and refreshes the
browser when the code changes.
```
But the start script in package is `"start": "ng serve",` and does not have the `--open` parameter needed to cause the launching of the app in the browser.

I've created PR #119 which adds the --open parameter and this corrects the problem for me.

**Comment by filipesilva** [comment]
Heya, you are right that the tutorial instruction don't reflect what actually happens. This happened because the tutorial was moved from using https://github.com/angular/quickstart to using Angular CLI, and in the quickstart the server opened automatically.

We don't want the server to open automatically in Angular CLI however, it has not opened automatically when running `npm start` and it would be surprising for users if that changed now for new project.

The right place to fix this is thus the docs themselves. Bugs for Angular.io are being tracked in https://github.com/angular/angular. I'll reopen your issue there.
