### ISSUE TITLE
Custom schematic returning an Observable fails with 'tree.branch is not a function' error

### ISSUE THREAD

**Issue by geneshap** [angular/devkit#271]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [X ] schematics
```
### Versions

v6.10.1/3.10.10/Windows 10

### Repro steps

1. Create custom schematic project, e.g. schematics @schematics/schematics:schematic --name my-schematic-collection
2. Change to my-schematic-collection folder
3. npm install
4. npm install --save rxjs
5. modify example code for my-schematic to return an Observable<Tree> instead of Tree object
    e.g. import "Observable" from "rxjs/Observable"; return Observable.of(tree);
6. npm run build
7. npm link (just to use it locally for now)
8. run schematics via following command: schematics my-schematic-collection:my-schematic
    This results in error: tree.branch is not a function

### Desired functionality

This should work (hopefully).

### Mention any other details that might be useful

WORK-AROUND found:
in global installation of the devkit, change the following in:
npm\node_modules\@angular-devkit\schematics\src\engine\schematic.js

from: if (result instanceof Observable_1.Observable) {
to: if (Symbol.observable in result) {

this issue most likely is related to the fact that instanceof does not work for objects passed between different javascript contexts.  This project already seems to be using Symbol.observable check in other places.

**Comment by mattma** [comment]
Installed with latest versions ( released two days ago )

```
    "@angular-devkit/core": "0.0.21",
    "@angular-devkit/schematics": "0.0.37",
```

A newly generated schematic project from the `@schematics/schematics` template. I am able to run `schematics myCollection:my-schematic` with the expected output. I assumed that I have set up everything correctly.

```
 ➜ schematics myCollection:my-schematic
  My Schematic: {}
CREATE /hello (5 bytes)
```

Try to run other **schematics** in the generated schematics without any modification, i run into the error: `tree.branch  is not a function`

```
 ➜ schematics myCollection:my-other-schematic
tree.branch is not a function
```

```
 ➜ schematics myCollection:my-full-schematic --name test                                                         1 ↵
tree.branch is not a function
```

The expected behavior should generate a set of files.


I have identified the issue that comes from [here](https://github.com/angular/devkit/blob/master/packages/angular_devkit/schematics/src/rules/base.ts#L47). When the reducer function is being called, [the tree](https://github.com/angular/devkit/blob/master/packages/angular_devkit/schematics/src/rules/call.ts#L76) method does not have the method of `branch`. Is it something easy to fix as a patch?

Hopefully it can be address in the version "@angular-devkit/schematics": "0.0.38" as a new patch release. @hansl

**Comment by hansl** [comment]
So I cannot seem to be able to reproduce with the default schematics :(

I've added a test in a new PR, which will show you an error in the case where you're doing something wrong.

**Comment by mattma** [comment]
Here is what I did.

Step 1

```
npm uninstall -g @angular-devkit/schematics
```

Step 2

Pull down `devkit` repo locally and use `npm link` to generate `schematics` binary


Step 3

Remove `@angular-devkit/schematics` from newly generated `@schematics/schematics` package.json file. so that it will use global `@angular-devkit/schematics`.

`tree.branch is not a function` error is gone. I can freely generate any collection. 

Hopefully it could help others.

Thanks for your help. @hansl

**Comment by mattma** [comment]
My goal is to create **schematics** that I can use with **angular-cli**. With the newly generated **schematics** template, I am able to run `schematics myCollection:my-schematic`, `schematics myCollection:my-full-schematic`.

Then I try to copy the factory of [enum folder](https://github.com/angular/devkit/tree/master/packages/schematics/angular/enum) along with [strings.ts](https://github.com/angular/devkit/blob/master/packages/schematics/angular/strings.ts) to my custom schematics, then add code to `src/collections.json`

```
    "enum": {
      "aliases": [ "e" ],
      "description": "Create an enumeration.",
      "factory": "./enum",
      "schema": "./enum/schema.json"
    },
```

Then I run `npm link` to create a global package, and create a new angular cli project with CLI version `1.6.0-rc.0`, then `npm link myCollection`

`ng g enum tester --collection myCollection`

```
Error: tree.branch is not a function
tree.branch is not a function
```

Same error occur. 

I noticed that `@angular-devkit/core` package version `0.0.21` does use `rxjs` but it does not have `rxjs` in the dependency list. So that whenever we use `@angular-devkit/core` as dependency or global package, any schematic project cannot be built successfully due to `Observable_1.observable.of is not defined`.  Is this the root cause ?  @hansl

**Comment by mattma** [comment]
@filipesilva @hansl I have tried with the latest patch release with **"@angular-devkit/core": "^0.0.22",**  **"@angular-devkit/schematics": "^0.0.38",**. The same issue is still existed with **"@angular/cli": "1.6.0-rc.1"**. 

I have checked the modified files that there is no [package.json](https://github.com/angular/devkit/blob/master/packages/angular_devkit/core/package.json) changes.

**Comment by hansl** [comment]
Seems like linking is the source. Let me analyze the issue and I’ll try to fix it for next week.

**Comment by mattma** [comment]
I tried to delete the `node_modules/@angular-devkit` folder (which contains three packages: schematics, core, build-optimizer), copy over from system global `@angular-devkit` built into my project `node_modules` folder. It gets rid of the error `tree.branch is not a function` but introduce a new one. 

```
module.js:538
    throw err;
    ^

Error: Cannot find module '@angular-devkit/schematics'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (_PATH_TO_MY_PROJECT_/node_modules/@angular/cli/utilities/schematics.js:9:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

there is a bug somewhere I guess. Thanks for looking into it. @hansl

**Comment by istiti** [comment]
if someone have quick workaround cauze can't create new project with --collection 
```
Error: tree.branch is not a function
tree.branch is not a function
```

**Comment by mattma** [comment]
@hansl Thank you for fixing the bug. I cannot verify on my local environment. I tried with `npm link`, and tried to copy built packages into the **angular-cli** generated project, no luck to get passed the same error message. 

I think **devkit** monorepos patch release is required. Does this PR need to be part of the `angular-cli` to make `ng g custom-schematic NAME` to work?

**Comment by mattma** [comment]
It works as expected with schematics **0.0.40** and angular-cli **1.6.0**. thanks @hansl

**Comment by geneshap** [comment]
Worked like a charm for me as well.  Thank you @hansl!

**Comment by kevincam3** [comment]
Works for me too. Thanks a bunch
