### ISSUE TITLE
need a local module options for ng g service

### ISSUE THREAD

**Issue by sharathc10** [angular/devkit#471]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Area
```
- [ ] devkit
- [ x] schematics
```

### Bug Report or Feature Request (mark with an `x`)
- [ ] bug report -> please search issues before submitting
- [ x] feature request

### Area

- [ ] devkit
- [ x] schematics

### Repro steps

in an angular CLI project (src/app)
>create a new directory e.g. service1-directory
>cd service1-directory
>ng  g service service1 --module=service1.module

this causes to create the service1 file in the service1-directory but the module file is supposed to be in src/app/..

### Desired functionality

This feature should allow the module file to be in the current directory and create one if it doesn't exist.  This could be done with an additional value in the schema.json file e.g. localModule

The command would be:
ng g service service1 --localModule=service1.module

What is the usecase?
We are looking to create categories of services in different directories with separate modules

**Comment by Brocco** [comment]
The CLI and it's schematics are not designed to generate items based upon arguments at this time. This was considered (and pushed for by me) but after discussing it was decided that if you'd like to generate a service with a module then as a user you should generate the module and then generate the service.

Otherwise there would be too many permutations of options to account for.

That being said, if you'd like to implement this in your own set of schematics for what works best for you, feel free. There's a blog post on the angular blog about creating custom schematics.
