### ISSUE TITLE
No declarations in build when set in compile options

### ISSUE THREAD

**Issue by NickClark** [angular/devkit#752]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

```
Node: v9.8.0
NPM: 5.6.0
macOS High Sierra
@ngTools/webpack: 1.10.2
```

### Repro steps

Do a basic build of typescript using ngTools, notice no `.d.ts` files.

### Desired functionality

I'm using this to build a component lib, but I need to include declaration files. It would be nice to have the corresponding `.d.ts` files for each entry.

**Comment by clydin** [comment]
The ngtools plugin and loader are designed for application development.  CLI 6.0 will contain library support leveraging [ng-packagr](https://github.com/dherges/ng-packagr).

**Comment by NickClark** [comment]
So I should be able to accomplish this now using the latest RC of angular/angular-cli and dherges/ng-packagr

**Comment by clydin** [comment]
The latest RC contains support (after creating a new project) for using `ng generate library ...` which will generate a library already configured with `ng-packagr`.  There is also the option to use `ng-packagr` standalone, if desired.  Note also that as a release candidate there may still be bugs present.  The library creation and generation story will also be improved within and beyond the 6.x timeframe.  If you have the time, please post any issues/concerns or feature requests related to the new capability as user input is important so that the feature can be improved moving forward.
